version: 0.0
os: linux

files:
  - source: \index.html
    destination: C:\inetpub\wwwroot\test_site

hooks:
  ApplicationStop:
    - location: scripts\stopsite.bat
      timeout: 300
      runas: Administrator
  BeforeInstall:
    - location: scripts\delsite.bat
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: scripts\startsite.bat
      timeout: 300
      runas: Administrator


